---
name: Perl-Critic-Compatibility
version: 0.999_001
author:
  - 'Elliot Shank <perl@galumph.com>'
abstract: Policies for Perl::Critic concerned with compatibility with older versions of Perl.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Perl::Critic: 1.083_001
  version: 0
build_requires:
  Test::More: 0
dynamic_config: 0
provides:
  Perl::Critic::Compatibility:
    file: lib/Perl/Critic/Compatibility.pm
    version: 0.999_001
  Perl::Critic::Policy::Compatibility::ProhibitThreeArgumentOpen:
    file: lib/Perl/Critic/Policy/Compatibility/ProhibitThreeArgumentOpen.pm
    version: 0.999_001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
